### PR TITLE
Adds additional licenses found in DAX datasets

### PR DESCRIPTION
**Pull request by djalova**
Adds the following licenses:

-  Creative Attribution-ShareAlike 3.0 

Will update PR as I find more licenses used in DAX datasets

### CODE REVIEW

**Comment by xuhdev** [comment]
Is this still in WIP? Could you rebase?

**Comment by xuhdev** [comment]
In case you missed this, the CI failed

**Review by xuhdev — CHANGES_REQUESTED** [review]
CI failed

**Comment by djalova** [comment]
@xuhdev Fixed lint issues

**Review by xuhdev — APPROVED** [review]
LGTM

**Pull request merged**
